<script setup>
const skills = ["Golang",
  "Fiber",
  "Java",
  "Kotlin (Native)",
  "Spring Boot",
  "C",
  "C++",
  "LibHTTP",
  "Rust",
  "Rocket",
  "Dart",
  "Flutter",
  "Python",
  "FastAPI",
  "Flask",
  "Swift",
  "Scala",
  "PHP",
  "Laravel",
  "Ruby",
  "Rails",
  "HTML5",
  "JavaScript",
  "TypeScript",
  "Node.js",
  "Express.js",
  "Vue.js",
  "Nuxt",
  "React (Native)",
  "Next.js",
  "jQuery",
  "HTMX",
  "alpine.js",
  "CSS3",
  "TailwindCSS",
  "Bootstrap",
  "Git",
  "Subversion",
  "Docker",
  "Podman",
  "Vulkan",
  "Metal",
  "OpenGL (ES)",
  "GLFW",
  "LWJGL",
  "SDL2",
  "MySQL",
  "PostgreSQL",
  "GraphQL",
  "MongoDB",
  "Redis",
  "memcached",
  "Ubuntu Linux",
  "RHEL",
  "Bash",
  "Zsh",
  "Postfix",
  "Dovecot",
  "SpamAssassin",
  "OpenDKIM",
  "NGINX",
  "ZFS",
  "KVM/QEMU",
  "Windows",
  "PowerShell",
  "Active Directory",
  "Microsoft IIS",
  "Microsoft Azure",
  "AWS",
  "GCP",
  "Vercel",
  "DigitalOcean",
  "VMware ESXi",
  "Hyper-V",
  "Proxmox",
  "Stripe",
  "PayPal",
  "MacOS",
  "iOS",
  "Android",
  "watchOS",
  "iPadOS",
  "Xcode",
  "JetBrains"
]

</script>

<template>
  <h3>Technical Experience</h3>
  <div class="grid grid-cols-2 md:grid-cols-4 gap-2 place-content-center font-display not-prose">
    <span
      class="flex flex-row justify-center items-center text-center gap-1 border px-2 select-none pointer-events-none font-mono"
      v-for="skill in skills">
      {{ skill }}
    </span>
  </div>
</template>

<style scoped></style>