when:
  - event: push
    branch:
      exclude: main

steps:
  - name: build
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: build
      with: npm
      frozen_lockfile: true
      ignore_node_modules: true
