when:
  - event: push
    branch: main

steps:
  - name: npm run build
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: build
      with: npm
      frozen_lockfile: true
      ignore_node_modules: true
  - name: scp deploy to nginx
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH_PRIVATE_KEY
      script:
        - echo "test"
        - ping 10.11.11.3