steps:
  - name: deploy
    image: appleboy/drone-scp
    when:
      - event: [push,tag,release]
        branch: main
    settings:
      host:
        from_secret: SSH_HOST
      username:
        from_secret: SSH_USERNAME
      port:
        from_secret: SSH_PORT
      key:
        from_secret: SSH_PRIVATE_KEY
      target:
        - /var/www/possiblemeatball.net
      source:
        - .vitepress/dist/*

depends_on:
  - build