steps:
  - name: npm run build
    image: codeberg.org/woodpecker-plugins/node-pm
    when:
      event: push
      branch:
        exclude: main
    settings:
      run: build
      with: npm
      frozen_lockfile: true
      ignore_node_modules: true
