name: deploy
on:
  push:
    branches: ["main"]
jobs:
  build:
    uses: possiblemeatball/portfolio/.github/workflows/build.yml@main
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: WireGuard tunnel
        uses: NexRX/WireGuard-Session@v1
        with:
          wg-client-b64: ${{ secrets.WG_CONF_B64 }}
          timeout-address: ${{ secrets.SSH_HOST }}

      - name: Run deploy script on remote server over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/portfolio
            git pull origin main
            npm ci
            npm run build --if-present
            restorecon -R /opt/portfolio
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S chown -R gh-actions:nginx dist/